[bumpver]
current_version = "v1.16.3"
version_pattern = "vMAJOR.MINOR.PATCH"
pre_commit_hook = "./update_cargo.sh"
commit = true
push = true

[bumpver.file_patterns]
"Cargo.toml" = [
    'version = "{pep440_version}"',
]
