[bumpver]
current_version = "v1.16.3"
version_pattern = "v{MAJOR}.{MINOR}.{PATCH}"
commit = true
push = true

[bumpver.file_patterns]
"include/downstream/version.hpp" = [
    '#define DSTREAM_VERSION "{version}"',
]
