name: Python CI
on:
  push:
    branches: [ python ]
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:

  style:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: ./style.sh

  requirements:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          sudo apt-get update -y
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: ./requirements.sh

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install -r requirements.txt
      - run: ./lint.sh

  test-downstream:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        module: [
          "test_downstream/test_auxlib",
          "test_downstream/test_dataframe",
          "test_downstream/test_dstream/test_compressing_algo",
          "test_downstream/test_dstream/test_hybrid_algo",
          "test_downstream/test_dstream/test_hybrid_algo_prefab",
          "test_downstream/test_dstream/test_steady_algo",
          "test_downstream/test_dstream/test_stretched_algo",
          "test_downstream/test_dstream/test_tilted_algo",
          "test_downstream/test_dsurf",
        ]
        python: ["3.10", "3.11", "3.12"]
        requirements: ["requirements.txt", "requirements-jit.txt"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install -r ${{ matrix.requirements }}
      - run: python3 -m pytest -n auto ${{ matrix.module }}

  validate-downstream:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        algo: [
          "dstream.compressing_algo",
          "dstream.hybrid_0_steady_1_stretched_2_algo",
          "dstream.hybrid_0_steady_1_tilted_2_algo",
          "dstream.steady_algo",
          "dstream.stretched_algo",
          "dstream.tilted_algo",
        ]
        op: [
          "assign_storage_site",
          "has_ingest_capacity",
          "lookup_ingest_times",
        ]
        requirements: ["requirements.txt", "requirements-jit.txt"]
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install -r ${{ matrix.requirements }}
      - run: python3 -m pip install . --upgrade
      - run: python3 -m downstream --version
      - run: python3 -m downstream.testing.debug_one 'python3 -m downstream' '${{ matrix.algo }}.${{ matrix.op }}'
      - run: python3 -m downstream.testing.validate_one 'python3 -m downstream' '${{ matrix.algo }}.${{ matrix.op }}'

  test-validators:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]
        requirements: ["requirements.txt", "requirements-jit.txt"]
        setup: ["sudo apt-get install -y pv", ""]
        which: ["debug", "validate"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - run: |
          sudo apt-get update -y
          ${{ matrix.setup }}
      - run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install -r ${{ matrix.requirements }}
      - run: python3 -m pip install .
      - run: python3 -m downstream -h
      # should detect correct output
      - run: python3 -m downstream.testing.${{ matrix.which }}_one 'python3 -m downstream' dstream.steady_algo.assign_storage_site
      - run: python3 -m downstream.testing.${{ matrix.which }}_all 'python3 -m downstream'
      # should detect incorrect output
      - run: python3 -m downstream.testing.${{ matrix.which }}_one 'echo 42' dstream.steady_algo.assign_storage_site && exit 1 || echo "expected fail"
      - run: python3 -m downstream.testing.${{ matrix.which }}_all 'echo 42' && exit 1 || echo "expected fail"
      # should detect crash
      - run: python3 -m downstream.testing.${{ matrix.which }}_one 'false' dstream.steady_algo.assign_storage_site && exit 1 || echo "expected fail"
      - run: python3 -m downstream.testing.${{ matrix.which }}_all 'false' && exit 1 || echo "expected fail"

  test-packaging:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m pip install setuptools pip --upgrade
          python3 -m pip install '.[testing]'
          rm -rf downstream
      # ignore warnings to reduce memory use
      # (there are a lot of deprecation warnings)
      - run: |
          python3 -m pytest -n auto -W ignore test_downstream

  # regression test for https://github.com/mmore500/hstrat/commit/c276530
  packaging-bdist:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build bdist
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install "setuptools==69.2.0" --upgrade
          python3 setup.py bdist_wheel
          tree dist
          deactivate
      - name: Upgrade pip
        run: python3 -m pip install setuptools pip --upgrade
      - name: Upgrade setuptools
        run: python3 -m pip install "setuptools==69.2.0" --upgrade
      - name: Install from bdist
        run: python3 -m pip install dist/*.whl
      - name: Test install
        run: |
          find . -type f -name '*.py' -exec rm {} \;
          python3 -c "import downstream; print(downstream.__version__)"

  # regression test for https://github.com/mmore500/hstrat/commit/c276530
  packaging-sdist:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build sdist
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install "setuptools==69.2.0" --upgrade
          python3 setup.py sdist
          tree dist
          deactivate
      - name: Upgrade pip
        run: python3 -m pip install setuptools pip --upgrade
      - name: Upgrade setuptools
        run: python3 -m pip install "setuptools==69.2.0" --upgrade
      - name: Install from sdist
        run: python3 -m pip install dist/*.tar.gz
      - name: Test install
        run: |
          find . -type f -name '*.py' -exec rm {} \;
          python3 -c "import downstream; print(downstream.__version__)"

  # regression test for https://github.com/mmore500/hstrat/commit/c276530
  packaging-source:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: python3 -m pip install setuptools pip --upgrade
      - name: Upgrade setuptools
        run: python3 -m pip install "setuptools==69.2.0" --upgrade
      - name: Install from source
        run: python3 -m pip install .
      - name: Test install
        run: |
          rm -rf *
          cd
          python3 -c "import downstream; print(downstream.__version__)"

  deploy-ghcr:
    name: Docker Image Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Tags
        id: set_tags
        run: |
          if [[ "${GITHUB_REF_NAME}" != *merge ]]; then
            echo "TAGS=latest,${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAGS=latest" >> $GITHUB_ENV
          fi
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/python' || startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ env.TAGS }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: mmore500/downstream
          registry: ghcr.io
          add_git_labels: true
